//
//To help in communication with the server get the exec_php
import { Idatabase } from '../../../schema/v/code/schema.js';
import { exec } from '../../../schema/v/code/server.js';
//
//Try to describe a students progress with the help of the editor class
//The main aim is to se the sql generated by the describe
(async () => {
    //
    //Try to describe the progress entity in the school db
    const result: [db: Idatabase, cnames: Array<string>, sql: string, max_records: string] =
        await exec('editor', ['progress', 'school'], 'describe', []);
    //
    //Run the query to get some sample results
    const progres = await exec('database', ['school'], 'get_sql_data', [result[2]]);
    //
    //Log a sample progress
    console.log(progres);
})();
