import { exec } from '../../../schema/v/code/server.js';
//
//Try to describe a students progress with the help of the editor class
//The main aim is to se the sql generated by the describe
(async () => {
    //
    //Try to describe the progress entity in the school db
    const result = await exec('editor', ['progress', 'school'], 'describe', []);
    //
    //RUn the query to get some sample results
    const progres = await exec('database', ['school'], 'get_sql_data', [result[2]]);
    //
    //Log a sample progress
    console.log(progres);
})();
